# Generated by Django 6.0.4 on 2026-06-10 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderPay',
            new_name='OrederPay',
        ),
    ]
