# Generated by Django 6.0.4 on 2026-06-10 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_orderpay_orederpay'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrederPay',
            new_name='OrderPay',
        ),
    ]
