# Generated by Django 6.0.4 on 2026-06-10 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_orederpay_orderpay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpay',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orders.order'),
        ),
    ]
